# This wrangler.toml file is not used for deploying the Pages project.
# It is needed so that Wrangler can run the d1 commands to create the db and process migrations.
name = "wildebeest"
main = "src/index.ts"
compatibility_date = "2022-12-05"
node_compat = true

# Specify your account id here so that all commands run agains the correct account.
# account_id = "<your account id>"

[[d1_databases]]
binding = "DATABASE"
database_name = "wildebeest"
# Replace this database_id with the id of the database created by `yarn deploy:init`.
database_id = "5d782c7f-e75d-470c-913b-69cd9f86dd27"
